### ISSUE TITLE
Would like to help

### ISSUE THREAD

**Issue by graanco** [nzapponi/homebridge-simplisafe3#10]
I've been working on the sensors system too... I see that you have done an awesome job... As for sensors....

Glass is the same a motion sensor just label it differently...
Leak sensor Homekit supports easy to add...
Smoke detector Homekit supports...
Freeze sensor is a temperature sensor...
Water sensor is another motion sensor...
Co2 Sensor is not mentioned and it is in HomeKit....

this is a quick copy from my code for supporting sensors

            case ss.SensorTypes.CarbonMonoxideSensor:
              newAccessory.addService(Service.CarbonMonoxideSensor, ss.SensorTypes[ss.sensors[sensor].type].replace('Sensor', ' Detector'));
              break;
            case ss.SensorTypes.ContactSensor:
              newAccessory.addService(Service.ContactSensor, ss.SensorTypes[ss.sensors[sensor].type].replace('Sensor', ' Sensor'));
              break;
            case ss.SensorTypes.GlassBreakSensor:
                newAccessory.addService(Service.MotionSensor, ss.SensorTypes[ss.sensors[sensor].type].replace('Sensor', ' Sensor'));
                break;
            case ss.SensorTypes.LeakSensor:
                newAccessory.addService(Service.LeakSensor, ss.SensorTypes[ss.sensors[sensor].type].replace('Sensor', ' Detector'));
                break;
            case ss.SensorTypes.MotionSensor:
              newAccessory.addService(Service.MotionSensor, ss.SensorTypes[ss.sensors[sensor].type].replace('Sensor', ' Sensor'));
              break;
            case ss.SensorTypes.SecuritySystem:
                newAccessory.addService(Service.SecuritySystem, "SimpliSafe Security System");
                break;
            case ss.SensorTypes.SmokeSensor:
              newAccessory.addService(Service.SmokeSensor, ss.SensorTypes[ss.sensors[sensor].type].replace('Sensor', ' Detector'));
              break;
            case ss.SensorTypes.TemperatureSensor:
              newAccessory.addService(Service.TemperatureSensor, ss.SensorTypes[ss.sensors[sensor].type].replace('Sensor', ' Sensor'));
              break;

Would like me to add the code for you?
If you are using the socket.io which I think you are... just place the system in test mode and then set the alarm  to get the coding...

Also in the config example you should add in the subscriptionId setting too

Change the only active to true... it is useless to get the other data since a subscription is required.

Okay I see that there is parts missing in the websocket connection... Are you still pulling for the sensor data??? Does SS push alerts about sensor data???

Also I would like to help in removing outside api code... Also GitHub seems to be behind versions.and lastly I just got a now response. I think that is because of the outside APIs.

**Comment by nikonratm** [comment]
Heh, I was helping out @graanco on the other project. Would like to help also. There are way too many SS homebridge plugins floating around, we should all concentrate on making the best one, happy to work on this one.

@graanco this plugin still uses a refresh timer like yours, seems like the only / best option for now.

**Comment by graanco** [comment]
I've been updating the code the my old project once I get it going I think... It will work on all versions of simple safe and allow multiple systems to be added.

Things I don't like seeing on this one is the plugins. I don't like them! my only issue is the socket.io. I think I will need to use that one.(too much code to rewrite)

**Comment by nzapponi** [comment]
Hi all, thanks for the offers to help out! I created this plugin rather than use other ones as I wanted to write something scalable in ES6 that included all the latest SimpliSafe 3 capabilities, including event subscriptions, etc.

This plugin subscribes to events for the alarm system itself, however SimpliSafe doesn't provide events for sensors (e.g. a door opening), so a frequent polling method is still required for those instances. This is to support use cases such as automation of the likes of "When a door is opened, turn the lights on".

@graanco, I am hesitant of adding the other sensor types you suggested, mostly because until SimpliSafe starts providing state information via API, there's not much point to display a sensor in HomeKit "just for the sake of it". It may even mislead users to set up automations that won't ever work, because SS3 just doesn't provide any data for those sensors.

... Unless I completely missed the point and either SS3 *does* provide data and I'm not aware of it, or there's another good reason for displaying those sensors in the Home app?

Finally, about this:
> Things I don't like seeing on this one is the plugins. I don't like them! my only issue is the socket.io. I think I will need to use that one.(too much code to rewrite)

Can you please elaborate on what you mean by "you don't like seeing plugins"?

Thanks all!

**Comment by nzapponi** [comment]
Actually, following the data provided in #11 , we **can** support a few extra sensors! 👍 

I'll add support for these this week, thanks.

**Comment by nikonratm** [comment]
@graanco I saw you made a comment in the other project about re-opening that one. Personally I think it’s crazy for all of us developers to have competing projects for the same purpose, why don’t we all just contribute to the same one (at the moment this seems like the most stable one)? If you have suggestions for nzapponi’s code you can fork his repo and suggest PR or something like that.

Again, as a developer and a user of this project I feel like we would all benefit from collaborating together.

**Comment by graanco** [comment]
if you seen what I wrote.... I didn't like the fact about the slow coding (too many hops) on his side and it still has loops running. That is worrying me... Also using other codes to get running too like how he using other plug ins. I am trying to stop all that... that is how I've been writing my code smaller and faster.

**Comment by graanco** [comment]
@nzapponi my thoughts on this...

Second pull socket IO client from the cloud and run it VM.Execute. That way it is alway up to date per each restart. 

You don't need AXIOS for http request. NODEJS has that built in already. 

Back in the beginning I was making different classes for each object on the system but discovered it slow down the code.

I will look into the cameras in more detail. I like using that code from outside modules too but again it will slow down the code. 

One of the great things about SS API they have a cfgs right up there on the website to pull too.

I am not sure on how your approach on things but I am after socket controlling the feed back. I even think the socket sends stuff back for V1, & 2. I will have to verify this again. Since, my last attempt didn't have it posting updates.

**Comment by nzapponi** [comment]
Thanks for the feedback.

> Pull socket IO client from the cloud and run it wm.runInThisContext. That way it is alway up to date per each restart.

This is a security risk and could potentially lead to unexpected behavior without any sort of version control.

> You don't need AXIOS for http request. NODEJS has that built in already.

Agreed - I'll remove it in a future release.

> Back in the beginning I was making different classes for each object on the system but discovered it slow down the code.

I doubt it has any sort of impact on performance other than the startup time - this is not a speed-critical application!

> I will look into the cameras in more detail. I like using that code from outside modules too but again it will slow down the code.

The ffmpeg dependency is purely for simplicity of installation, but you can use your own version of ffmpeg too. Other than installation speed, it shouldn't have an impact on overall performance.

> One of the great things about SS API they have a cfgs right up there on the website to pull too. They use the angular class in their code...

Their web app is created in Angular but it doesn't mean anything. As long as you hit the APIs correctly!

**Comment by graanco** [comment]
I think I found it....
warningSensorOpen

I think sensorRestored would be the close?

**Comment by nzapponi** [comment]
I’ll test it but I think those only trigger during the exit countdown.

**Comment by graanco** [comment]
hey you just up your code and you still missed this??


              case ss.ssEventContactIds.alarmSmokeDetectorTriggered:
              case ss.ssEventContactIds.alarmWaterSensorTriggered: 
              case ss.ssEventContactIds.alarmFreezeSensorTriggered:
              case ss.ssEventContactIds.alarmCoSensorTriggered:
              case ss.ssEventContactIds.alarmEntrySensorTriggered:
              case ss.ssEventContactIds.alarmMotionOrGlassbreakSensorTriggered:
.......

                     // 4: Motion sensor
                    // 6: Glass break sensor
                    // 7: CO sensor


so you can add them......

**Comment by graanco** [comment]
some dumb reason I am getting server not found in my code for the camera... are you getting the same issue?

https://52.6.84.216/v1/uuid/flv?x=1280 Server returned 404 Not Found

**Comment by nzapponi** [comment]
It works for me!
What happens if you replace the IP address with `media.simplisafe.com` and try to open it up in a browser? Does it load anything? It may be a DNS issue..
