### ISSUE TITLE
FFmpeg exited with code 1

### ISSUE THREAD

**Issue by JoshuaHolme** [nzapponi/homebridge-simplisafe3#101]
I tried to add a path to an FFmpeg installation to help make the cameras load faster in the home app, but now I’m getting the error `Error: FFmpeg exited with code 1`

**Comment by nikonratm** [comment]
Hi @JoshuaHolme , if the plugin works with the bundled plugin I would guess the issue is to do with your installation / configuration of ffmpeg. Have you confirmed it works using basic commands? eg https://www.tecmint.com/ffmpeg-commands-for-video-audio-and-image-conversion-in-linux/

If it is working separately please provide your config.json, more log output and any further details.

Obviously this feature works for others so thinking it’s something specific to your setup.

**Comment by JoshuaHolme** [comment]
After trying to point it to my own instance of FFMpeg without it working, I tried to remove the option from the config file and now it still won’t work even with the option removed (trying to use the default behavior). Is there a way to re setup Homebridge and this plugin without losing my configuration in the home app? Or is that just not possible?

**Comment by nikonratm** [comment]
Yes, exit code `1` is generally saying there was an error.

If you are using Config UI X it has a handy backup / restore function, otherwise just as long as you keep your `config.json` file and the `persist` and `accessories` nothing should be lost. But in general you can use npm to [un-install](https://stackoverflow.com/questions/13066532/how-to-uninstall-npm-modules-in-node-js) and [re-install](https://github.com/nzapponi/homebridge-simplisafe3#usage) the same way you originally did and this shouldn't affect your installation.

Let us know how you get on.

**Comment by JoshuaHolme** [comment]
Tried reinstalling the plugin but received this error
![Screen Shot 2020-05-07 at 11 31 09 AM](https://user-images.githubusercontent.com/25995502/81313808-5708c080-9056-11ea-89e4-60967593b15a.png).

**Comment by nikonratm** [comment]
Joshua, you either did not install the plugin correctly and / or your config.json is incorrect. I can tell by the line `Loading plugin homebridge-simplisafe-security-system-3` which refers to a [completely different plugin than this one](https://github.com/muhlman/homebridge-simplisafe-security-system#readme) (one that looks abandoned). This one is `homebridge-simplisafe3`. Please share you `config.json` file and / or try re-installing.

Again, I highly recommend you look into [Config UI X](https://github.com/oznu/homebridge-config-ui-x) as it will take care of a lot of this for you and prevent user errors.

Also btw, when sharing console output copy & pasted text is usually easier than a screenshot.

And FYI, there is a [Homebridge Discord channel](https://discord.gg/RcV7fa8) and a [sub-Reddit](https://www.reddit.com/r/homekit) which can be helpful.

Let us know how you get along.

**Comment by JoshuaHolme** [comment]
Very weird. I'm installing with `npm install -g --unsafe-perm homebridge-simplisafe3`, and this is my `config.json`

```{
  "bridge": {
    "name": "Homebridge",
    "username": "**:**:**:**:**:**",
    "port": *****,
    "pin": "***-**-***"
  },

  "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
  "ports": {
    "start": *****,
    "end": *****,
    "comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
  },
  "accessories": [
  ],

  "platforms": [
        {
            "platform": "homebridge-simplisafe3.SimpliSafe 3",
            "name": "Home Alarm",
            "auth": {
                "username": "*********",
                "password": "*********"
            },
            "cameras": true

        }
    ]
}
```

I'll have to look into the Config UI X, but I think it could also be my home bridge installation is a bit messed up itself. I'm thinking of reinstalling it and starting from scratch, but I wanted to try to avoid having to relabel all of my window and door sensors.

**Comment by nikonratm** [comment]
Config looks OK. Perhaps you need to uninstall that other plugin too `npm uninstall -g homebridge-simplisafe-security-system-3`

Yea failing that I would consider starting from scratch. Theres a helpful [wiki page](https://github.com/homebridge/homebridge/wiki/How-To-Fix-Node.js-Install-Issues-On-Linux) about how to totally do that (including removing node) and then I'd recommend [re-installing with Config UI X from the jump](https://github.com/oznu/homebridge-config-ui-x#installation-instructions), it has built-in tools to make installing, restarting etc. easier if youre not super comfortable with CLI.

**Comment by nikonratm** [comment]
Ps. looking again at your screenshot it doesnt look like the plugin is installed (at least at the time of that screenshot). Take a look at that wiki guide to remove everything, you can backup a few files and not lose any of your actual devices etc.

**Comment by JoshuaHolme** [comment]
I'm on Windows, the guide looks like it's only for Linux. Is there one for windows? Or could you just point me to the few files that need to be backed up?

**Comment by nikonratm** [comment]
The files to backup are the same just in different locations. Here's the [Windows guide](https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Windows-10) including the locations of said files (`%HOMEPATH%\.homebridge`)

**Comment by JoshuaHolme** [comment]
Seems to be working again after the reinstall, and I'm now using the UI. Cameras still take about 15 seconds of buffering to load though, and CPU on my computer running home bridge never goes up past 15%. Any reasons for this or tips to speed it up?

**Comment by nikonratm** [comment]
15 seconds sounds a bit long but a major part of the delay is SS has really slow servers to stream the video. The other part of this most certainly comes down to your ffmpeg install, e.g. whether you've set it up for hardware accceleration etc. Thats a bit outside the scope of this plugin but theres more info and some relevant links here: https://github.com/nzapponi/homebridge-simplisafe3/blob/master/docs/raspberry-pi-ffmpeg.md

Glad to hear its working.
