### ISSUE TITLE
Plugin should respect Homebridge storage path

### ISSUE THREAD

**Issue by nikonratm** [nzapponi/homebridge-simplisafe3#102]
Was getting `Warning: could not save SS config file. SS-ID will vary` on every start, looked into it and if you use a custom Homebridge storage path (which happens with a "usual" install of Config UI X) then the plugin ignores it.

Already have a fix for this.

**Comment by nikonratm** [comment]
Hey @nzapponi, this fix will leave some people's config file "orphaned" and create a new one, this seems like no big deal, agreed?

And one question about npm and releasing new versions: this fix for example is small and I dont think worth releasing a whole new version so I would just plan to release as part of the next version. So for now I will just submit and merge a PR into master branch, *not* do any of the `npm version` stuff and then the next time we do a release it'll be included since branches will come from this new master—correct? I also wasnt sure about the changelog, is it best practice to leave it alone for now until the next release or should I add v1.5.1 and a mention of this bug fix to the changelog in anticipation of the next release?

**Comment by nzapponi** [comment]
Hi @nikonratm , yes that's correct!
I would leave the changelog as is until you're ready to release a new version.
No need to do any `npm version` either - the GitHub Action I created does it for you. All you need to do whenever you want to release a new version to the public is to update the changelog and create the release on GitHub.

**Comment by nikonratm** [comment]
Awesome, gotcha!

Is there an easy way to have the changes from changelog.md pulled over to the release notes? Config UI X (which is getting more and more popular now that the devs are very actively working on it and is even included in the default Homebridge install instructions) uses the release notes. Obviously if not, its super easy to copy + paste them manually (for example I did already for 1.5.0) =)

**Comment by nzapponi** [comment]
No I'm afraid we need to copy and paste them!

**Comment by nikonratm** [comment]
Hey @nzapponi , for v1.5.1 I didn't run `npm version` but I just noticed the package.json & -lock files weren't updated which meant the plugin would keep showing as v1.5.0, so it seems like we do need to run `npm version`. Anyway, I had to release 1.5.2 to fix this, FYI =)
