### ISSUE TITLE
Speedy snapshots

### ISSUE THREAD

**Issue by nikonratm** [nzapponi/homebridge-simplisafe3#115]
@nzapponi I wanted to get your opinion on this before releasing, Ive been testing for a few days and it seems to work great. Im not sure you have a camera that you really use but this is especially useful for doorbell cameras.

The basic idea is to take a snapshot every X seconds, store it and serve that for snapshot requests as long as its not too old. My biggest concern was getting rate-limited but so far its not an issue because I dont think they rate-limit media.simplisafe.com

This is in the [feature/speedy-snapshots branch](/nzapponi/homebridge-simplisafe3/tree/feature/speedy-snapshots) (specifically around lines [207](https://github.com/nzapponi/homebridge-simplisafe3/blob/4f91b2801378980d75cc91d7fb2b758f1021d211/src/accessories/simplicam.js#L207), [261](/nzapponi/homebridge-simplisafe3/blob/4f91b2801378980d75cc91d7fb2b758f1021d211/src/accessories/simplicam.js#L261) and [322](https://github.com/nzapponi/homebridge-simplisafe3/blob/4f91b2801378980d75cc91d7fb2b758f1021d211/src/accessories/simplicam.js#L322) of simplicam.js) if you have any thoughts on the idea or are able to test a little?

**Comment by nzapponi** [comment]
Very cool! I don't have a door bell so I can't test that, but I do have a couple of SimpliCams and it definitely speeds up the process of getting a snapshot!

Also, I'm not surprised they don't rate limit media.simplisafe.com, given that you could have any number of cameras in the house and, when an event is triggered, all of them need to stream to SimpliSafe at the same time!

I'd say let's keep testing to make sure there are no limits whatsoever and then let's release it!

Great work!

**Comment by nikonratm** [comment]
Grr, unfortunately theres a problem with this because somehow the frequent grabbing of images causes motion detection not to work. As a compromise I did manage to convert snapshots to use mjpeg which does seem to be faster than using ffmpeg but not as dramatically so as the local ones did.

Oh well, some improvement! 🤷🏽‍♂️
