### ISSUE TITLE
Use ffmpeg-for-homebridge

### ISSUE THREAD

**Issue by nikonratm** [nzapponi/homebridge-simplisafe3#116]
[ffmpeg-for-homebridge](https://github.com/homebridge/ffmpeg-for-homebridge) seems like best-maintained project for homebridge and will enable better docker support as this package comes bundled with [oznu/docker-homebridge](https://github.com/oznu/docker-homebridge)

Currently waiting on a new release with libspeex (see [ffmpeg-for-homebridge/pull/8](/homebridge/ffmpeg-for-homebridge/pull/8))

**Comment by nzapponi** [comment]
Great stuff!
