### ISSUE TITLE
SSAPI socket error: Not authorized

### ISSUE THREAD

**Issue by mbriney** [nzapponi/homebridge-simplisafe3#125]
**Describe The Bug:**

Items are not responding in the Home.app.  Login details are verified, I can login to the Simplisafe website with no issue.

**To Reproduce:**

**Expected behavior:**

[**Logs:**]()

```
[5/30/2020, 9:46:05 AM] [Home Alarm] SSAPI socket error: Not authorized
```
This error repeats every second.

**Homebridge Config:**

```
json
        {
            "name": "Home Alarm",
            "auth": {
                "username": "m******@******.com",
                "password": "************"
            },
            "cameras": true,
            "debug": true,
            "sensorRefresh": 15,
            "persistAccessories": false,
            "resetSimpliSafeId": false,
            "platform": "homebridge-simplisafe3.SimpliSafe 3"
        },
```

**Screenshots:**

<img width="232" alt="Screen Shot 2020-05-30 at 9 52 36 AM" src="https://user-images.githubusercontent.com/253367/83330149-54674880-a25b-11ea-85ef-5ffba96d7f51.png">

**Environment:**

* **Plugin version**:  homebridge-simplisafe3 v1.6.2
* **Node.js Version**:  v12.16.3
* **NPM Version**: v6.14.4
* **Homebridge Version**:  Version 1.1.0
* **Operating System**:  Deepin Stable (15.11) - Debian base
--

**Comment by mbriney** [comment]
I may have figured this out.  If I disable camera support the plugin starts working again.  It also stops the error and the rest of my devices function again too.  I am also running homebridge-camera-ffmpeg v1.2.2 in my setup, it could be a conflict perhaps?

**Comment by nikonratm** [comment]
Hi @mbriney, is your Homebridge debug logging enabled (see https://github.com/homebridge/homebridge/wiki/Basic-Troubleshooting#debug-mode )? If not please re-create and paste logs here, there should be a bit more output. I am assuming your alarm is working OK? The alarm and the cameras use the same socket connection so if one works they both should (unless theres an issue =)

**Comment by mbriney** [comment]
I am getting this error again now with the cameras disabled.  Here are the detailed logs.  I did scramble the personal identifiers below.

_____

		'set-cookie': [
			'AWSALB=QxAdsGNRPJLLYOGi10YsV5i53QBtABVu9JMndErVp8z9M3PTZVy2+/0uqB/qAO5ZZAICrif6+BfMzNm73PFdQbvNERO1DVEwh/EFKumL9wATEP633l0S28FxBEMN; Expires=Sat, 04 Jul 2020 19:36:28 GMT; Path=/',
			'AWSALBCORS=QxAdsGNRPJLLYOGi10YsV5i53QBtABVu9JMndErVp8z9M3PTZVy2+/0uqB/qAO5ZZAICrif6+BfMzNm73PFdQbvNERO1DVEwh/EFKumL9wATEP633l0S28FxBEMN; Expires=Sat, 04 Jul 2020 19:36:28 GMT; Path=/; SameSite=None; Secure'
		],
		'access-control-allow-origin': '*',
		'access-control-allow-methods': 'GET,PUT,POST,DELETE,OPTIONS',
		'access-control-allow-headers': 'Content-Type, Authorization, Content-Length, X-Requested-With, Content-Disposition',
		etag: 'W/"97-EFz9wMWasJ7uq+F2fechslO8zZI"'
	},
	config: {
		url: '/api/token',
		method: 'post',
		data: '{"refresh_token":null,"grant_type":"refresh_token"}',
		headers: {
			Accept: 'application/json, text/plain, */*',
			'Content-Type': 'application/json;charset=utf-8',
			'User-Agent': 'axios/0.19.2',
			'Content-Length': 51
		},
		auth: {
			username: '4df55627-46b2-4e2c-866b-XXXXXXXXX.WebApp.simplisafe.com',
			password: ''
		},
		baseURL: 'https://api.simplisafe.com/v1',
		transformRequest: [ [Function: transformRequest] ],
		transformResponse: [ [Function: transformResponse] ],
		timeout: 0,
		adapter: [Function: httpAdapter],
		xsrfCookieName: 'XSRF-TOKEN',
		xsrfHeaderName: 'X-XSRF-TOKEN',
		maxContentLength: -1,
		validateStatus: [Function: validateStatus]
	},
	request: ClientRequest {
		_events: [Object: null prototype] {
			socket: [Function],
			abort: [Function],
			aborted: [Function],
			error: [Function],
			timeout: [Function],
			prefinish: [Function: requestOnPrefinish]
		},
		_eventsCount: 6,
		_maxListeners: undefined,
		outputData: [],
		outputSize: 0,
		writable: true,
		_last: true,
		chunkedEncoding: false,
		shouldKeepAlive: false,
		useChunkedEncodingByDefault: true,
		sendDate: false,
		_removedConnection: false,
		_removedContLen: false,
		_removedTE: false,
		_contentLength: null,
		_hasBody: true,
		_trailer: '',
		finished: true,
		_headerSent: true,
		socket: TLSSocket {
			_tlsOptions: [Object],
			_secureEstablished: true,
			_securePending: false,
			_newSessionPending: false,
			_controlReleased: true,
			secureConnecting: true,
			_SNICallback: null,
			servername: 'api.simplisafe.com',
			alpnProtocol: false,
			authorized: true,
			authorizationError: null,
			encrypted: true,
			_events: [Object: null prototype],
			_eventsCount: 10,
			connecting: false,
			_hadError: false,
			_parent: null,
			_host: 'api.simplisafe.com',
			_readableState: [ReadableState],
			readable: true,
			_maxListeners: undefined,
			_writableState: [WritableState],
			writable: false,
			allowHalfOpen: false,
			_sockname: null,
			_pendingData: null,
			_pendingEncoding: '',
			server: undefined,
			_server: null,
			ssl: [TLSWrap],
			_requestCert: true,
			_rejectUnauthorized: true,
			parser: null,
			_httpMessage: [Circular],
			[Symbol(res)]: [TLSWrap],
			[Symbol(asyncId)]: 1471642,
			[Symbol(kHandle)]: [TLSWrap],
			[Symbol(kSetNoDelay)]: false,
			[Symbol(lastWriteQueueSize)]: 0,
			[Symbol(timeout)]: null,
			[Symbol(kBuffer)]: null,
			[Symbol(kBufferCb)]: null,
			[Symbol(kBufferGen)]: null,
			[Symbol(kCapture)]: false,
			[Symbol(kBytesRead)]: 0,
			[Symbol(kBytesWritten)]: 0,
			[Symbol(connect-options)]: [Object]
		},
		connection: TLSSocket {
			_tlsOptions: [Object],
			_secureEstablished: true,
			_securePending: false,
			_newSessionPending: false,
			_controlReleased: true,
			secureConnecting: true,
			_SNICallback: null,
			servername: 'api.simplisafe.com',
			alpnProtocol: false,
			authorized: true,
			authorizationError: null,
			encrypted: true,
			_events: [Object: null prototype],
			_eventsCount: 10,
			connecting: false,
			_hadError: false,
			_parent: null,
			_host: 'api.simplisafe.com',
			_readableState: [ReadableState],
			readable: true,
			_maxListeners: undefined,
			_writableState: [WritableState],
			writable: false,
			allowHalfOpen: false,
			_sockname: null,
			_pendingData: null,
			_pendingEncoding: '',
			server: undefined,
			_server: null,
			ssl: [TLSWrap],
			_requestCert: true,
			_rejectUnauthorized: true,
			parser: null,
			_httpMessage: [Circular],
			[Symbol(res)]: [TLSWrap],
			[Symbol(asyncId)]: 1471642,
			[Symbol(kHandle)]: [TLSWrap],
			[Symbol(kSetNoDelay)]: false,
			[Symbol(lastWriteQueueSize)]: 0,
			[Symbol(timeout)]: null,
			[Symbol(kBuffer)]: null,
			[Symbol(kBufferCb)]: null,
			[Symbol(kBufferGen)]: null,
			[Symbol(kCapture)]: false,
			[Symbol(kBytesRead)]: 0,
			[Symbol(kBytesWritten)]: 0,
			[Symbol(connect-options)]: [Object]
		},
		_header: 'POST /v1/api/token HTTP/1.1\r\n' +
			'Accept: application/json, text/plain, */*\r\n' +
			'Content-Type: application/json;charset=utf-8\r\n' +
			'User-Agent: axios/0.19.2\r\n' +
			'Content-Length: 51\r\n' +
			'Host: api.simplisafe.com\r\n' +
			'Authorization: Basic NGRmNTU2MjctNDZiMi00ZTJjLTg2NmItMTUyMWIzOTVkZWQyLldlYkFwcC5zaW1wbGlzYWZlLmNvbTo=\r\n' +
			'Connection: close\r\n' +
			'\r\n',
		_onPendingData: [Function: noopPendingOutput],
		agent: Agent {
			_events: [Object: null prototype],
			_eventsCount: 2,
			_maxListeners: undefined,
			defaultPort: 443,
			protocol: 'https:',
			options: [Object],
			requests: {},
			sockets: [Object],
			freeSockets: {},
			keepAliveMsecs: 1000,
			keepAlive: false,
			maxSockets: Infinity,
			maxFreeSockets: 256,
			maxCachedSessions: 100,
			_sessionCache: [Object],
			[Symbol(kCapture)]: false
		},
		socketPath: undefined,
		method: 'POST',
		insecureHTTPParser: undefined,
		path: '/v1/api/token',
		_ended: true,
		res: IncomingMessage {
			_readableState: [ReadableState],
			readable: false,
			_events: [Object: null prototype],
			_eventsCount: 3,
			_maxListeners: undefined,
			socket: [TLSSocket],
			connection: [TLSSocket],
			httpVersionMajor: 1,
			httpVersionMinor: 1,
			httpVersion: '1.1',
			complete: true,
			headers: [Object],
			rawHeaders: [Array],
			trailers: {},
			rawTrailers: [],
			aborted: false,
			upgrade: false,
			url: '',
			method: null,
			statusCode: 400,
			statusMessage: 'Bad Request',
			client: [TLSSocket],
			_consuming: false,
			_dumped: false,
			req: [Circular],
			responseUrl: 'https://4df55627-46b2-4e2c-866b-XXXXX.WebApp.simplisafe.com:@api.simplisafe.com/v1/api/token',
			redirects: [],
			[Symbol(kCapture)]: false
		},
		aborted: false,
		timeoutCb: null,
		upgradeOrConnect: false,
		parser: null,
		maxHeadersCount: null,
		reusedSocket: false,
		_redirectable: Writable {
			_writableState: [WritableState],
			writable: true,
			_events: [Object: null prototype],
			_eventsCount: 2,
			_maxListeners: undefined,
			_options: [Object],
			_redirectCount: 0,
			_redirects: [],
			_requestBodyLength: 51,
			_requestBodyBuffers: [],
			_onNativeResponse: [Function],
			_currentRequest: [Circular],
			_currentUrl: 'https://4df55627-46b2-4e2c-866b-XXXXXX.WebApp.simplisafe.com:@api.simplisafe.com/v1/api/token',
			[Symbol(kCapture)]: false
		},
		[Symbol(kCapture)]: false,
		[Symbol(kNeedDrain)]: false,
		[Symbol(corked)]: 0,
		[Symbol(kOutHeaders)]: [Object: null prototype] {
			accept: [Array],
			'content-type': [Array],
			'user-agent': [Array],
			'content-length': [Array],
			host: [Array],
			authorization: [Array]
		}
	},
	data: {
		error: 'invalid_request',
		error_description: 'Invalid body was provided: child "refresh_token" fails because ["refresh_token" must be a string]'
	}
}
[6/27/2020, 3:36:28 PM] [Home Alarm] SSAPI socket error: Not authorized
[6/27/2020, 3:36:29 PM] [Home Alarm] SSAPI socket error: Not authorized

**Comment by shamoon** [comment]
@mbriney there should be a little of the logs prior to what you pasted. A couple things:

- As I mentioned, this is likely not related to cameras. Regardless of how many cameras you have the plugin uses a single web socket connection for 'real time' events.
- Does the plugin recover from this? If not what do you have to do, restart HB?
- This issue is clearly intermittent, do you have any way you've figured out how to reproduce it?

I cant tell if this is just SS having an error (in which case the plugin should still be able to handle it) or if there is a race condition error. Again, if you are able to reproduce that would be helpful.

**Comment by scamden** [comment]
@mbriney fyi, unsure if this is your issue, but I got this same error because I had failed to click the multi factor link sent to my email
