### ISSUE TITLE
Remove Axios dependency

### ISSUE THREAD

**Issue by nzapponi** [nzapponi/homebridge-simplisafe3#13]
Based on feedback in #10

**Comment by graanco** [comment]
also you use a lot of other dependencies are they all really used?  

under my code I only use two,,,,,, socket-io client and FFmpeg

**Comment by nzapponi** [comment]
All the other dependencies are either devDependencies for code listing or for polyfilling to older Node versions.

What's the problem with using other dependencies? Surely I'd rather rely on a well-maintained, open source implementation of a feature than to re-implement it myself with the risk of introducing bugs?

**Comment by graanco** [comment]
So... Http or Https by Nodejs API isn't well maintain?  I have no issue with your decision to close this and I have moved away from homebridge since it is way behind the HAP code... Good luck with your code...

**Comment by nzapponi** [comment]
Obviously the native modules are well maintained, but Axios provides a number of capabilities, such as managing access tokens and response codes. 

I could implement these myself in this module, but I would run into the risk of creating additional bugs, and duplicating the work that someone else has already done and that are actively maintaining. 

Isn’t that the point of open source anyway?

**Comment by graanco** [comment]
I do understand about not reinventing the wheel, but I was an assembler programer. I always felt keep it small and simple.

**Comment by nzapponi** [comment]
Ah makes sense ;)
