### ISSUE TITLE
Requested accessory was not registered by the plugin

### ISSUE THREAD

**Issue by aaronschendel** [nzapponi/homebridge-simplisafe3#133]
**Describe The Bug:**
[7/3/2020, 5:10:52 PM] Error: The requested accessory 'SimpliSafe 3' was not registered by the plugin 'homebridge-simplisafe3'.
    at Plugin.getAccessoryConstructor (/usr/local/lib/node_modules/homebridge/src/plugin.ts:101:13)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:348:30
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:330:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:156:12)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)

This error occurs when starting home bridge. Config below.

**To Reproduce:**
1. Install home bridge via
`sudo npm install -g --unsafe-perm homebridge`

2. Install this plugin via
`sudo npm install -g --unsafe-perm homebridge-simplisafe3`

3. Add appropriate configuration details

4. Run homebridge

**Expected behavior:**
I expect it to load home bridge without error.

[**Logs:**]()

```
Paste Homebridge Logs here
```

**Homebridge Config:**

```
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
	"platforms": [],
	"accessories": [{
		"accessory": "homebridge-simplisafe3.SimpliSafe 3",
		"name": "Alarm System",
		"auth": {
			"username": "[myEmail]",
			"password": "[myPassword]"
		}
	}]


}
```

**Screenshots:**

**Environment:**

* **Plugin version**:  1.6.5
* **Node.js Version**:  12.18.2
* **NPM Version**:  6.14.5
* **Homebridge Version**:  1.1.1
* **Operating System**:  macOS 10.15.5

**Comment by aaronschendel** [comment]
Hey all - first of all thank you for making this plugin, it is way more full featured than a previous homebridge plugin I was using! I am sure I am just doing something wrong but after looking through homebridge documentation and your previous GitHub issues nothing is popping out at me. Thanks in advance.

**Comment by aaronschendel** [comment]
I knew I'd figure it out. I had it under "accessories" instead of "platforms" - whoops! Feel free to close - sorry about that!

**Comment by shamoon** [comment]
Hi @aaronschendel Yes, the logs would indicate you have not installed the plugin correctly and / or have an issue with your homebridge setup.

Especially if the command line is not in your comfort zone (but honestly in general it’s super useful) I can’t recommend highly enough you install Config UI X, see: https://github.com/oznu/homebridge-config-ui-x (and if you’re using a Pi you may want to look at the official image also mentioned in that link). It has a GUI for installing plugins, updating them etc. If you prefer not to use that, I would try reinstalling homebridge and then this plugin again.
