### ISSUE TITLE
Can't setup multiple SimpliSafe instances

### ISSUE THREAD

**Issue by madrobby** [nzapponi/homebridge-simplisafe3#142]
**Is your feature request related to a problem? Please describe:**
Yes. I've two separate SimpliSafe alarm systems in two separate buildings, but the buildings share WiFi and a Homebridge instance. Right now, only one configuration is possible in the config file.

**Describe the solution you'd like:**
Add the ability to have multiple instances, either by making `subscriptionId` an array or by allowing multiple configuration blocks so you can use different auths as well.

**Additional context:**
I've tried adding multiple configuration blocks but I'm getting this error:
```
[8/17/2020, 10:46:51 AM] The dynamic platform SimpliSafe 3 from the plugin homebridge-simplisafe3 seems to be configured multiple times in your config.json. This behaviour was deprecated in homebridge v1.0.0 and will be removed in v2.0.0!
```

I'm also getting occasional rate limiting errors. I don't know if that's related to me trying multiple configs or not.
```
[8/17/2020, 10:46:52 AM] [Home Alarm] SSAPI token refresh failed, request blocked (rate limit?).
[8/17/2020, 10:46:52 AM] [Home Alarm] Accessory refresh failed due to rate limiting or connectivity
[8/17/2020, 10:46:52 AM] [Home Alarm] Accessory refresh failed due to rate limiting or connectivity
```

**Comment by shamoon** [comment]
Hi @madrobby 

Hmm, this seems like a pretty specific use case, two alarms in different buildings that share a homebridge install. Besides the fact that it's not really supported by homebridge out-of-the-box, it doesn't make a ton of logical sense to me (different buildings would seem to mean different "Homes" in HomeKit no?). Anyway I'm not aware of an easy way to implement this and I'm not sure it will be widely-enough used to justify. The obvious solution I see would be to run two separate instances of homebridge for each building. It's really pretty trivial to do so, see ￼￼https://github.com/homebridge/homebridge/issues/1736

**Comment by madrobby** [comment]
@shamoon It's the same home, just two buildings side-by-side. Some other plugins, like https://github.com/hjdhjd/homebridge-unifi-protect2 support this scenario fine (they allow multiple controllers, which is equivalent to multiple security systems).

**Comment by shamoon** [comment]
Oh I see what you mean so just kinda multiple alarms. Hmm, I'll look into this. Can't promise anything yet tho cause I do think it's somewhat limited use-case

**Comment by volcachi** [comment]
I am having the same issue.. I have two unique "subscriptionId", as I have two monitoring plans on the same network. One is for the main house, the other is for a separate studio space on my property. Finding your plugin has been a lifesaver, but I really need this functionality. Is there anyway at all to allow for two subscriptionId's? Thank you for your support! @shamoon

**Comment by kbanning** [comment]
Another user here with multiple systems on one property. They need to be segregated due each system having different uses/needs. I would love to be able to use two siumplisafe SYSTEM_IDs  in one homebridge instance. My current plan is to install another home bridge instance on a separate Pi.  Thank you for your support! @shamoon

**Comment by volcachi** [comment]
@kbanning I switched to Home Assistant and will never look back. Milestones more powerful and responsive than homebridge. The Simplisafe integration alone is as powerful as it gets and it recognizes multiple systems out of the box. It took me a year of painfully tweaking Homebridge before making the switch and my home automation experience has never been better. Highly recommend!
