### ISSUE TITLE
"Subscription ID is ambiguous"

### ISSUE THREAD

**Issue by cakefornoreason** [nzapponi/homebridge-simplisafe3#15]
This could be an issue in my setup, since I had to remove chowielin's SimpliSafe plugin to install this one instead, but I can't get it to load the system or any accessories. From the Homebridge logging:

```
[9/14/2019, 9:08:41 AM] [Home Alarm] An error occurred while refreshing accessories
[9/14/2019, 9:08:41 AM] [Home Alarm] Error: Subscription ID is ambiguous
    at SimpliSafe3.getSubscription (/usr/lib/node_modules/homebridge-simplisafe3/simplisafe.js:247:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[9/14/2019, 9:08:41 AM] [Home Alarm] Refreshing accessories
```

Running on an RPi 3, Rasbian Stretch, Node.js v10.16.3. Any ideas what I might be doing wrong, or is this perhaps a true bug of some sort?

**Comment by nikonratm** [comment]
Comes from https://github.com/nzapponi/homebridge-simplisafe3/blob/77e482a81b42011f2c087ebce65e03075847a724/src/simplisafe.js#L228 , looks like it can't find the subscription ID. Im assuming you are in fact paying for a SS **interactive** plan?

**Comment by cakefornoreason** [comment]
Yes, my current plan is the $24.99 plan tbT I believe is the interactive one. I use the first-party app and I’ve successfully used other web-based Homebridge plugins, so I don’t think the plan is the problem.

Any other info that might be helpful?

**Comment by nzapponi** [comment]
@cakefornoreason do you have multiple subscriptions or systems with your user account?

**Comment by cakefornoreason** [comment]
That could be part of it—I have only one active system but my account does have record of two systems because there was a weird ordering issue when I first set it up that resulted in a canceled order. I don’t know of a way to remove that record, though...

**Comment by nzapponi** [comment]
Do you happen to know your subscription number? If you do, you should add “subscriptionId”: “xxxx” to your config in config.json.

If you don’t know it, I’ll edit the code over the next couple days so that it tells you which subscriptions are available and you can pick one.

**Comment by cakefornoreason** [comment]
I see an “account” number that’s 7 numbers and a letter—is that the format or am I looking for something else?

**Comment by cakefornoreason** [comment]
Okay, so after a little bit of testing, I was able to get it working by designating a subscriptionId as you suggested. Interestingly, though, I was only able to find that number because the Homebridge logs from the older SimpliSafe plugin I switched away from showed it in the logging. I don't think the sub number appears anywhere on the website, so the selectability feature seems like a good long-term fix.

Hope this info helps, and thanks for being so responsive!

**Comment by graanco** [comment]
You should use the serial not sid ... Sid is hard to find where serial is in the App and on the base unit

**Comment by nzapponi** [comment]
@cakefornoreason I have updated the support for multiple accounts, and following on @graanco 's advice, I have changed it to require Account # / Serial Number rather than subscriptionId, since the Account # is something you can find on the hardware itself.

The update comes with release v1.2.3 (commit c82e2f0be0f856673b42b53e81e01a4c05ee208d).

When you update, can you please edit your `config.json` file and replace the number you entered in the `subscriptionId` with the Account # of your device? You'll find it at the bottom of your base unit.

Thanks
