### ISSUE TITLE
Entry Sensor Poll Interval Too Infrequent

### ISSUE THREAD

**Issue by BCooon** [nzapponi/homebridge-simplisafe3#150]
### Is your feature request related to a problem? Please describe:
Poll interval too infrequent for standard door entry sensor behavior

### Describe the solution you'd like:
Option to change poll interval, or simply set it lower globally (1 second, for instance)

### Describe alternatives you've considered:
No other options I am aware of - there does not seem to be an configurable option today.

**Comment by shamoon** [comment]
Hi @BCooon This does in fact exist already though it was not explicitly mentioned in the readme. I have updated it, see https://github.com/nzapponi/homebridge-simplisafe3/blob/master/README.md#sensorrefresh

**Comment by shamoon** [comment]
Ps. I agree, ideally we could set it lower but that will likely get your IP temporarily blocked (let us know if otherwise!)

**Comment by BCooon** [comment]
@shamoon do you know the threshold at which SS would block my IP? I would like to set it at 3 or 5 seconds ideally. Thank you.

**Comment by shamoon** [comment]
I have never had success below 8 seconds but admittedly its been a while since I last tested. Curious to know where you end up.
