### ISSUE TITLE
Error with duplicate subscription IDs

### ISSUE THREAD

**Issue by jamieaquila** [nzapponi/homebridge-simplisafe3#17]
Simplisafe is returning two subscriptions with the same ID. Even if setting this ID, I receive: `Error: Multiple subscriptions found. Edit your config.json file and add a parameter called "subscriptionId": "YOUR ACCOUNT NUMBER". The account numbers found were: XXXXXXXX, XXXXXXXX.` where both account numbers are the same.

I can also see this in my Simplisafe account. 

<img width="830" alt="image" src="https://user-images.githubusercontent.com/6360221/65279244-6650f300-daf3-11e9-950d-2129227812ad.png">

**Comment by jamieaquila** [comment]
To note: A call to Simplisafe solved this but it was a nightmare to explain to a level I tech. No longer a blocker issue for me, but could occur for anyone that has moved their base to a new location.

**Comment by nzapponi** [comment]
That's great to know, thanks @jamieaquila ! I'll see if I can solve it by filtering out inactive locations.
