### ISSUE TITLE
Cameras Not Working

### ISSUE THREAD

**Issue by nikonratm** [nzapponi/homebridge-simplisafe3#18]
I realize camera support is sorta experimental now but wondering if you have any insights into my setup. I got it installed, running Raspberry Pi 3 with Raspbian 4.19.57, no docker. The cameras show up in Home app but when I click into a stream I just get "no response" and the slashed-through camera icon always shows. My config is nearly identical to your example one. Output is below, it just looks like it immediately stops right after starting and "duration" shows N/A... Something is up.

If you have any thoughts on how to go about debugging / testing etc I can give it a shot, I'm also a dev but this is a bit outside my wheelhouse.

And also, thanks, this software has been super helpful and rock solid since I switched over to using it.

```
Sep 27 10:46:44 homebridge[7275]: [9/27/2019, 10:46:44 AM] [Home Alarm] Start streaming video from Front Door
Sep 27 10:46:44 homebridge[7275]: [9/27/2019, 10:46:44 AM] [Home Alarm] ffmpeg version N-95098-gb9f8ab3 Copyright (c) 2000-2019 the FFmpeg deve
Sep 27 10:46:44 homebridge[7275]:   built with gcc 8 (Raspbian 8.3.0-6+rpi1)
Sep 27 10:46:44 homebridge[7275]:   configuration: --pkg-config-flags=--static --extra-cflags='-fPIC -I/home/pi/ffmpeg_build/include' --extra-l
Sep 27 10:46:44 homebridge[7275]:   WARNING: library configuration mismatch
Sep 27 10:46:44 homebridge[7275]: [9/27/2019, 10:46:44 AM] [Home Alarm]   avutil      configuration: --prefix=/usr --extra-version=1+rpt1 --too
Sep 27 10:46:44 homebridge[7275]:   avcodec     configuration: --prefix=/usr --extra-version=1+rpt1 --toolchain=hardened --libdir=/usr/lib/arm-
Sep 27 10:46:44 homebridge[7275]:   avformat    configuration: --prefix=/usr --extra-version=1+rpt1 --toolchain=hardened --libdir=/usr/lib/arm-
Sep 27 10:46:44 homebridge[7275]:   avdevice    configuration: --prefix=/usr --extra-version=1+rpt1 --toolchain=hardened --libdir=/usr/lib/arm-
Sep 27 10:46:44 homebridge[7275]:   avfilter    configuration: --prefix=/usr --extra-version=1+rpt1 --toolchain=hardened --libdir=/usr/lib/arm-
Sep 27 10:46:44 homebridge[7275]:   swscale     configuration: --prefix=/usr --extra-version=1+rpt1 --toolchain=hardened --libdir=/usr/lib/arm-
Sep 27 10:46:44 homebridge[7275]:   swresample  configuration: --prefix=/usr --extra-version=1+rpt1 --toolchain=hardened --libdir=/usr/lib/arm-
Sep 27 10:46:44 homebridge[7275]:   postproc    configuration: --prefix=/usr --extra-version=1+rpt1 --toolchain=hardened --libdir=/usr/lib/arm-
Sep 27 10:46:44 homebridge[7275]:   libavutil      56. 35.100 / 56. 22.100
Sep 27 10:46:44 homebridge[7275]:   libavcodec     58. 59.100 / 58. 35.100
Sep 27 10:46:44 homebridge[7275]:   libavformat    58. 33.100 / 58. 20.100
Sep 27 10:46:44 homebridge[7275]:   libavdevice    58.  9.100 / 58.  5.100
Sep 27 10:46:44 homebridge[7275]:   libavfilter     7. 59.100 /  7. 40.101
Sep 27 10:46:44 homebridge[7275]:   libswscale      5.  6.100 /  5.  3.100
Sep 27 10:46:44 homebridge[7275]:   libswresample   3.  6.100 /  3.  3.100
Sep 27 10:46:44 homebridge[7275]:   libpostproc    55.  6.100 / 55.  3.100
Sep 27 10:46:44 homebridge[7275]: [9/27/2019, 10:46:44 AM] [Home Alarm] [https @ 0x13f4f20] No trailing CRLF found in HTTP header.
Sep 27 10:46:49 homebridge[7275]: [9/27/2019, 10:46:49 AM] [Home Alarm] Input #0, flv, from 'https://52.0.178.189/v1/92164ee3d6314674e721434070
Sep 27 10:46:49 homebridge[7275]:   Duration: N/A, start: 0.000000, bitrate: N/A
Sep 27 10:46:49 homebridge[7275]: [9/27/2019, 10:46:49 AM] [Home Alarm]
Sep 27 10:46:49 homebridge[7275]:     Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 20 fps, 2
Sep 27 10:46:49 homebridge[7275]:     Stream #0:1: Audio: speex, 16000 Hz, mono, s16, 7 kb/s
Sep 27 10:46:49 homebridge[7275]: [9/27/2019, 10:46:49 AM] [Home Alarm] Stopped streaming
```

**Comment by nzapponi** [comment]
@nikonratm what version of ffmpeg are you using? Is it the one that ships with the plugin?

**Comment by nikonratm** [comment]
`ffmpeg version N-95098-gb9f8ab3`
I followed [your instructions](https://github.com/nzapponi/homebridge-simplisafe3/blob/master/docs/raspberry-pi-ffmpeg.md) exactly (except I did have to install a couple of missing libraries) and installed at `/usr/local/bin/ffmpeg`

**Comment by virtualjad** [comment]
Running into an identical issue in my environment. Nothing out of the ordinary in debug. I hear the shutter open for about a sec then closes with output "stopped streaming". 

I was initially having SSL issues as ffmpeg was compiled without openssl -- i needed to add libssl-dev recompile to fix. 

Happy to help troubleshoot if needed.

- Homebridge (latest) on Pi 3B+ v1.3
- Raspbian 10 (buster)

**Comment by nzapponi** [comment]
Great point @virtualjad !

Could you please post instructions here too so I can upload the readme?

**Comment by virtualjad** [comment]
[https://stackoverflow.com/questions/31514949/ffmpeg-over-https-fails](https://stackoverflow.com/questions/31514949/ffmpeg-over-https-fails
)

Comment 14 identifies the needed `libssl-dev`. I then had to recompile ffmpeg following your details.

**Comment by nzapponi** [comment]
@nikonratm any chance you can try it out and see if it solves the issue for you too?

**Comment by virtualjad** [comment]
Another important observation - even with openssl errors gone, I wasn't able to get streaming going with the codecs used in the sample. So instead, only specify the ffmpegPath parameter and restart HB. This is what ultimately worked in my env:

```
        {
            "platform": "homebridge-simplisafe3.SimpliSafe 3",
            "name": "Home Alarm",
            "auth": {
                "username": "mickey@disney.com",
                "password": "steamboat"
            },
            "cameras": true,
            "sensorRefresh": 15,
            "cameraOptions": {
                "ffmpegPath": "/usr/local/bin/ffmpeg"
            }
        },
```

(this assumes no other issues are popping up in debug)

**Comment by nikonratm** [comment]
Amazing @virtualjad that fixed it for me! I didn't need to re-compile or anything, just removed all the parameters except `ffmpegPath`

Awesome.
