### ISSUE TITLE
Camera 480p stream provides wrong resolution

### ISSUE THREAD

**Issue by nzapponi** [nzapponi/homebridge-simplisafe3#21]
With the camera set to 720p the stream worked. But under 480p settings for the camera(I think this is new which is good for lower bandwidth homes) it doesn't seem to be pulling the video.... Under mine I see this for the stream 848x480 and it is off it should be 640x480.

_Originally posted by @graanco in https://github.com/nzapponi/homebridge-simplisafe3/issues/19#issuecomment-539515387_

**Comment by graanco** [comment]
I fixed it on my side.... I changed the x to y for the API camera call... and sent all the camera setting to the camerasource. I remove the video request part and only have the setting apply the video information and the audio stream is in 1000 so I had to / 1000....

I will upload my source one moment.

**Comment by graanco** [comment]
I update the camera settings again... I learned the the user might change setting while actively running. Also, I broke apart the video push and pull resolution... The use might request 720p/1080p but the camera is only on a 480p stream. So I hope this works.

**Comment by nzapponi** [comment]
Cannot reproduce. I tried with my camera at 480p and it works fine with the standard configuration!
