### ISSUE TITLE
Improve support for removing accessories

### ISSUE THREAD

**Issue by nzapponi** [nzapponi/homebridge-simplisafe3#24]
The streams remain cached and HomeKit still shows the camera in the list of accessories.

**Comment by nzapponi** [comment]
This may no longer be particularly relevant if we're changing the way we manage camera - see #28

**Comment by nzapponi** [comment]
There is some issue that causes `removeAccessory()` to be called on every restart. Commenting out 

https://github.com/nzapponi/homebridge-simplisafe3/blob/a28284985b8c234b37b63c8907c49f9ac345af44/src/index.js#L115

isn't a permanent solution.

**Comment by graanco** [comment]
It would be nice if the socket event fired if SS had a removal of a device. Right now we can only add.
