### ISSUE TITLE
Camera Event Listener Doesn't Reconnect on Socket Disconnect

### ISSUE THREAD

**Issue by nikonratm** [nzapponi/homebridge-simplisafe3#26]
End result is you stop receiving notifications after a disconnect.

Problem is scoping the camera events (using name, serial or whatever) shouldn't include DISCONNECT events, as it is currently camera wont reconnect. Will submit a PR for this.

**Comment by nikonratm** [comment]
@nzapponi I submitted a new PR for this because I still wasn't seeing the cameras reconnect on `DISCONNECT`, I think I've solved it for real now. The issue was (I think) that the parts of `subscribeToEvents` that actually ran `callback('DISCONNECT')` were all wrapped in an `else` from `if (this.socket) {` in other words they only ran the _first time_ `subscribeToEvents` is called, so just for the alarm, not for the cameras. I changed by moving those parts of the event handlers outside the if block.

**Comment by nzapponi** [comment]
Merged, thanks for this.
