### ISSUE TITLE
SS3 init failed

### ISSUE THREAD

**Issue by hubartt** [nzapponi/homebridge-simplisafe3#31]
After updating today - the platform fails to initialize.

There is quite a bit in the console after:

`[Security] SS3 init failed
[Security] { status: 403,
  statusText: 'Forbidden',`

Everything still shows up in HomeKit but arming/disarming don't work and camera doesn't respond.

Console also says:

`[Security] Device not found!
[Security] Remove accessory`

Let me know what information would be helpful to provide.

**Comment by nikonratm** [comment]
403 forbidden usually is a credentials issue. Did you double-check your credentials in the config and make sure you can login to the website / app and ensure you can login? Also sometimes you can get locked out for a few hours...

**Comment by hubartt** [comment]
You’re right. I’m unable to access SimpliSafe on my home WiFi at all. Just happened to update at a similar time. Thanks.
