### ISSUE TITLE
Feature Request: Add CO Sensor

### ISSUE THREAD

**Issue by murphmr** [nzapponi/homebridge-simplisafe3#33]
Would it be possible to add support for the CO sensor similar to the Smoke Sensor no that the CO sensors are readily available again.  See device info below:
10/22/2019, 10:19:38 AM] [Home Alarm] Sensor not (yet) supported: CO Main
[10/22/2019, 10:19:38 AM] [Home Alarm] {
  setting: {},
  deviceGroupID: 0,
  name: 'Laundry 2',
  status: {
    test: false,
    endOfLife: false,
    lowSensitivity: false,
    tamper: false,
    malfunction: false,
    triggered: false
  },
  type: 7,
  serial: '00000000',
  flags: { swingerShutdown: false, lowBattery: false, offline: false }
}

**Comment by nikonratm** [comment]
I submitted a PR for this pending merge by the boss @nzapponi

**Comment by nikonratm** [comment]
BTW, I dont have one to test, @murphmr will have to test and let us know if any issues.

**Comment by nzapponi** [comment]
@murphmr I have just pushed this out in v1.2.10. Can you please update the plugin, test the CO detector and report here whether it works as it should?

Thanks!

**Comment by murphmr** [comment]
@nikonratm CO Detector looks good to me: 
Here is the log from startup...
[10/23/2019, 10:05:30 PM] [Home Alarm] Refreshing accessories
[10/23/2019, 10:05:30 PM] [Home Alarm] Sensor not found, adding...
[10/23/2019, 10:05:30 PM] [Home Alarm] Refreshing sensor state
[10/23/2019, 10:05:30 PM] [Home Alarm] Add accessory
[10/23/2019, 10:05:30 PM] [Home Alarm] Updated current state for CO Main: false, false, false, false

In HomeKit it is showing up with status for Status Tamperer and Carbon Monoxide Detected
