### ISSUE TITLE
Errors on docker log

### ISSUE THREAD

**Issue by tasansal** [nzapponi/homebridge-simplisafe3#4]
Hey, I am getting these errors from my home bridge running on docker. Any ideas?

My username, password, and the config file is fine. I am running Simplisafe 3, home bridge with docker on a Synology NAS, has an intel celeron quad core CPU.

![Screen Shot](https://user-images.githubusercontent.com/13684161/60608209-85f23e00-9d84-11e9-82a5-7bc46d7b64f6.png)

**Comment by nzapponi** [comment]
Looks like you need to update Node to v10 or higher.
I will update the documentation to reflect this requirement.

**Comment by tasansal** [comment]
Makes sense, thank you. After upgrading it worked like a charm. Thanks for all the effort!
