### ISSUE TITLE
SimpliSafe is blocking public IP 

### ISSUE THREAD

**Issue by kaicherry** [nzapponi/homebridge-simplisafe3#44]
Per the issue opened within the last 24 hours, SimpliSafe IS blocking this. After shutting down hb, uninstalling, etc.

This is with a sensor refresh *above* 30 secs (which adds of course, a bit of an 'uncomfortable' latency to some automations, "but")...SimpliSafe is definitely, actively blocking this, assuming changing the refreshFrequency is actually working.

Can this be investigated further?

**Comment by nzapponi** [comment]
@kaicherry this repository is not an official SimpliSafe product and as such we have no way of investigating further.

My experience is that too many calls will cause SS to block the IP for some time. Usually after 30 mins or so it's unblocked...

I use the default sensor refresh and rarely get this issue, but then again I don't really use the SimpliSafe app anymore so the number of total API calls is pretty limited.

HTH

**Comment by nzapponi** [comment]
Just FYI, this package already does try to optimize the # of API calls it makes... For instance it makes a single API call to fetch data for all sensors, rather than one per sensor.
