### ISSUE TITLE
Repeated No Response

### ISSUE THREAD

**Issue by JoshuaHolme** [nzapponi/homebridge-simplisafe3#54]
This plugin is fantastic! One issue I've noticed is fairly often when I open up the home app all of the accessories try to update and then default to `No Response`. If I force quit the home app and re open it usually fixes it, but not always. Any insight into this?

**Comment by nikonratm** [comment]
Joshua, do you have any other plugins installed on Homebridge, and do they experience the same thing? The "No Response" issue is one that has been incredibly widespread with iOS 13. It has many different possible causes / remedies (though no true "silver bullet" Im aware of). I have had issues with it myself but improved (not 100% gone) after much troubleshooting. If you take a peek around the web you'll find some ideas (and lots of other people with the same thing unfortunately):
- https://www.reddit.com/r/homebridge/search/?q=no%20response&restrict_sr=1
- https://www.reddit.com/r/HomeKit/search/?q=no%20response&restrict_sr=1
- https://www.reddit.com/r/HomeKit/comments/bi0bp1/no_response_a_constant_irritation_with_homekit/
- https://www.reddit.com/r/homebridge/comments/e3vcmi/my_homebridge_devices_are_very_slowly_loading_no/
- https://github.com/nfarina/homebridge/issues/2089

The potential causes are so varied it is likely out of the scope of this—again, unless you are certain it is isolated to this plugin. One thing I have very frequently seen is that networking changes are a solution for many. But generally, solutions can include:
- Resetting hubs e.g. AppleTV/HomePod
- Setting homebridge server to static IP
- Disabling IPv6 or certain other router settings (obviously totally variable by router)
- Changing routers
- Hoping Apple fixes this in a future release
- The list goes on...

If it is indeed isolated to this plugin please provide logs any logs etc. at the times you experience this.

**Comment by JoshuaHolme** [comment]
From what you're saying it seems like it could be a HomeKit thing in general. I've noticed that lately my Ecobee thermostat has been having connection issues too, even though that's officially HomeKit compatible. I don't have any other plugins installed, but I'm assuming that could be the issue. I wasn't sure if it was an API call limit that could be expected or anything like that which is why I asked here.

One more thing I was questioning. Figuring out the door sensors seemed to be straightforward (open the door/window and see which one changed to open on the home app) But how should I determine which water sensor/smoke alarm is which?

**Comment by JoshuaHolme** [comment]
Also, is there any documentation on changing the resolution of the doorbell cameras? I saw in one of the issues they talked about a 640 vs 720 setting, I just can't find how to change it.

**Comment by nikonratm** [comment]
Yea, hopefully Apple can improve the reliability issues. Have a look at some of the suggestions out there though.

The names of the sensors should carry over when you set things up.

Generally speaking there’s no need to change any resolution settings for the camera in the plugin. Your settings in SimpliSafe will determine the resolution of the input stream and the plugin & HomeKit handle downsizing for a particular device (eg smaller resolution on watch etc).

Please close this issue when you have a chance.

**Comment by JoshuaHolme** [comment]
Hmm. None of my names carried over from SimpliSafe when I set it up. Thank you for the info though!
