### ISSUE TITLE
TypeError: Cannot read property ‘name’ of null

### ISSUE THREAD

**Issue by thedandroid** [nzapponi/homebridge-simplisafe3#58]
Homebridge now fails to start after updating with plugin with error in title.

**Comment by nikonratm** [comment]
Hi Daniel, I can confirm this plugin is still in working order from the latest release (which was in fact just a reverting back to a previously-stable release). This type of error is often related to an error in the config file or some other issue beyond this plugin. Please consider asking for help on [Reddit](https://www.reddit.com/r/homebridge/) or similar forum. If you are certain it is the plugin, please provide more information e.g. how to reproduce and more detailed logs.

**Comment by nikonratm** [comment]
Also see #4 and #5 , you'll note both were not truly "plugin" issues.

**Comment by thedandroid** [comment]
Okay. Haven’t changed my config for the last 7 months that it’s been running. Literally saw the plugin had an update, updated it and homebridge failed to start with that error in the log. I’ll figure it out on my own. Thanks.

**Comment by nikonratm** [comment]
Is it possible the update failed? Please circle back here if you figure it out (again, or if you do think its related to the plugin), might be helpful for someone in the future.
