### ISSUE TITLE
Home app status text does not show if sensors are door or window

### ISSUE THREAD

**Issue by stingray75** [nzapponi/homebridge-simplisafe3#59]
In the Home app I would like to see at a glance if I have left any doors or windows open.  If my sensors are set to ‘contact sensor’ they show up in the status summary text - which is great - but if I set it them to ‘door’ or ‘window’ they only show up when I click details.

Leaving the sensors as “contact sensor” means they don’t display well in eve (as the status for closed is yes rather than closed) and they don’t look as nice in the Home app.

Is this a HomeKit or homebridge issue?

**Comment by nikonratm** [comment]
Hi @stingray75 this is definitely nothing to do with homebridge or this plugin, it’s a HomeKit question. Consider asking on reddit or the like.

But, I think if you click into any sensor accessory and go to it’s settings > “Status and Notifications” > **Include in Status** you’ll find what you’re after.

**Comment by stingray75** [comment]
Thanks, if I select “include in status” it shows the sensor in details (as an icon) but not on the summary screen as text. Changing it back to contact sensor make it appear on the summary screen as well. I’ll fire this question to the HomeKit reddit. Thanks
