### ISSUE TITLE
Automations Unreliable Because of setCharacteristic?

### ISSUE THREAD

**Issue by nikonratm** [nzapponi/homebridge-simplisafe3#66]
Im embarrassed to admit how long this took me to figure out (imagine me opening & closing my front door and my family looking at me like I'm crazy) but I think I have. To describe the issue, I have a few automations based on SS sensors which weren't being consistent:
- Open / closing windows disables / enables thermostat.
- Opening / closing doors turns on a light _and turns it off after 5 minutes_
- Alarm automatically sets to "Home" at 1AM every night.

To try and debug I enabled Homebridge debugging and saw some curious output:
```
Fri, 31 Jan 2020 09:22:51 GMT EventedHTTPServer [x.x.x.23] HTTP request: /characteristics
Fri, 31 Jan 2020 09:22:51 GMT HAPServer [xx:xx:xx:xx:xx:xx] HAP Request: PUT /characteristics
Fri, 31 Jan 2020 09:22:51 GMT Accessory [Homebridge] Processing characteristic set: [{"aid":11,"iid":9,"ev":false},{"aid":11,"iid":10,"ev":false}]
Fri, 31 Jan 2020 09:22:51 GMT Accessory [Homebridge] Unregistering Characteristic "Contact Sensor State" for events
Fri, 31 Jan 2020 09:22:51 GMT Accessory [Homebridge] Unregistering Characteristic "Status Low Battery" for events
```
That seems to show Homebridge unregistering listeners for the contact sensor for my front door. Interestingly I noticed the IP was also my iPhone.

Then when the door opens:
`
Fri, 31 Jan 2020 09:08:31 GMT EventedHTTPServer [xa.x.x.23] Sending HTTP event '11.9' with data: {"characteristics":[{"aid":11,"iid":9,"value":1}]}
`

My home hub (ATV) didn't seem to be listening and this is when I noted that the automations would work if the home app is open (on any device) because the device would register as a listener. So it seems the bug can be triggered by some combination of setting up an automation, running it at least once, maybe opening the Home.app on other device(s) and then the automation will fail.

After much searching, I *think* this is because the in the sensor code the characteristics are being changed with [`setCharacteristic`](https://github.com/KhaosT/HAP-NodeJS/blob/bace3b682fa664993a1d5504ffed42b5c08fed4c/src/lib/Service.ts#L283) (which then calls [`setValue`](https://github.com/KhaosT/HAP-NodeJS/blob/bace3b682fa664993a1d5504ffed42b5c08fed4c/src/lib/Characteristic.ts#L585)). In looking around, lots of people describe issues like this (see https://github.com/KhaosT/HAP-NodeJS/issues/543 https://github.com/nfarina/homebridge/issues/1006 https://github.com/nfarina/homebridge/issues/1182 ). So I think what we need to use is [`updateCharacteristic`](https://github.com/KhaosT/HAP-NodeJS/blob/bace3b682fa664993a1d5504ffed42b5c08fed4c/src/lib/Service.ts#L289) (which then calls [`updateValue`](https://github.com/KhaosT/HAP-NodeJS/blob/bace3b682fa664993a1d5504ffed42b5c08fed4c/src/lib/Characteristic.ts#L628)). The difference between the two is that `setValue` (or `setCharacteristic`) seems to only work when there's a set listener, which BTW in my mind would create a loop? I dunno).

After doing this I can reliably see my hub receiving sensor events when the state changes. I created a PR for this.

*But*, I think there is a second bug which has nothing to do with this plugin which is that HomeKit has all kinds of problems with automations that include "turn off after", see https://www.reddit.com/r/HomeKit/comments/d9ln5c/turn_off_light_after_x_time_has_stopped_working/ https://www.reddit.com/r/HomeKit/comments/deebmr/ios_13_broken_automatically_shut_off_switch_after/ that I think is out of the scope of this.

Would love some feedback on this, not sure if I'm just going crazy and the above is inaccurate...

**Comment by nikonratm** [comment]
Update: as I found elsewhere, using https://github.com/nitaybz/homebridge-delay-switch seems to solve the _turn off after_ issue (for now! 🤞🏽). The basic setup is now:
- Create delay switch for each item you want to be able to turn off, e.g. "Front Light Delay Switch". Set the delay on this (in Homebridge config) to be whatever you want, e.g. 5 minutes (= 30,000 miliseconds)
- Automation 1: when door opens (SimpliSafe contact sensor) → turn on _Front Light_ **and** turn on _Front Light Delay Switch_. Make sure **Turn Off** is set to _Never_
- Automation 2: when "Front Light Delay Switch" turns off → turn off _Front Light_

Again, I believe this issue was the intersection of these two bugs, I still think PR #67 is important.

**Comment by nzapponi** [comment]
I've done some digging and merged PR #67 .

Using `updateCharacteristic` vs `setCharacteristic` makes no difference. `updateCharacteristic` is syntactically more correct (hence why I merged the PR in), but the reality is that the code behind the scenes does the same thing when no listener is set up (which was the case everywhere we swapped from `setCharacteristic` to `updateCharacteristic`.

I have done some testing with the automations you mentioned and Homebridge debugging turned on: my feeling is that Apple TV is not good at handling hubs (like Homebridge) that reboot. I could replicate some of the issues you've had around registering/unregistering characteristic events, but try this:

1. Turn Homebridge debugging on
2. Set up an automation based on a contact sensor
3. Close Home on all devices and disconnect from Wi-Fi
4. Restart Homebridge - you will notice that Apple TV won't register for characteristic events
5. Try to open the contact sensor - the automation will not work. Close the contact sensor again
6. Now restart Apple TV - when it comes back on, you will see that it does register for characteristic events
7. Try to open the contact sensor - now the automation should work, and so will the "Turn off after..."

Do you see the same behavior?

Now, try this as well:
1. Restart Homebridge - at this point, Apple TV won't register for characteristic events again
2. Try to open the contact sensor - the automation should not work
3. Using a phone on cellular connection, open the Home app - this will "wake up" Apple TV, which will ask for characteristic values to Homebridge on behalf of the phone **and** register for characteristic events
4. Quit the Home app on your phone
5. Try to open the contact sensor again - the automation should now work

If you see the same behaviors above, I believe that it's then an Apple TV thing, not a Homebridge nor a plugin issue.

Any thoughts?

**Comment by nikonratm** [comment]
Appreciate the testing + time 🙏🏽

I'm closing this issue because I think we've done (more than!) due diligence about this plugin and I agree if there are remaining issues its somewhere else in the chain. I saw the logic of `updateValue` vs `setValue` are redundant but also wasn't sure if there were any effects on registering/de-registering listeners that might be related.

In trying to reproduce the bugs you describe, I do see mostly the same behavior but what has been driving me really crazy this whole time is that my "when door opens turn on light" automation has always been the most unreliable while the "when windows open turn off AC" has been solid—regardless of restarting the hub, etc. I wonder if there are some recent tvOS changes that have exacerbated / created this issue. It's also worth noting that HAP-NodeJS is well ahead of what's currently bundled with Homebridge, so perhaps updates will help.

Again, closing this, I'll look through HB/HAP-NodeJS issues and see if this has been raised/fixed but seems like a pretty major issue so if can be addressed from the HB/HAP-NodeJS side (as opposed to just waiting for Apple) seems worth it.

Again, thanks for all the effort.

**Comment by nzapponi** [comment]
Great! Also, I guess the problem can’t be the light bulb itself, right?..

Homebridge does need to update the HapJS version it uses, it would also help in supporting cameras without the need of adding them manually to HomeKit!

**Comment by nikonratm** [comment]
It could be but in my case its a 'dumb' bulb and a smart switch, Lutron, which is by far the most solid 'smart' home device I've ever used, they are totally solid, so yea, I think its somewhere in the tvOS—Homebridge (HAP-NodeJS) pipeline.
