### ISSUE TITLE
config.schema.json was not installed through npm command

### ISSUE THREAD

**Issue by muzzymate** [nzapponi/homebridge-simplisafe3#68]
config.schema.json was not downloaded when I upgraded to 1.4.3 by the command "npm install -g homebridge-simplisafe3". Config-UI-X did not see the file and did not present the Settings button. Restarted the instance just to make sure before checking. 

I manually downloaded the config.schema.json file and placed it in my C:\Users\chuck\AppData\Roaming\npm\node_modules\homebridge-simplisafe3 folder. It wasn't in the folder yet but I could see the index.js, simplisafe.js, and Accessories folder. Restarted the instance and was able to see the Setting button.

**Comment by nikonratm** [comment]
I can confirm this. Don’t see anything obvious in package.json or .gitignore, I don’t have npm access, I think @nzapponi will have to sort it out.

**Comment by nzapponi** [comment]
Yeah sorry, my fault, I need to fix the release script to include the new schema file. I’ll push a patch out today.
