### ISSUE TITLE
No longer respecting dir passed to -U command-line option, failing on launch at mkdir '/home/homebridge/.homebridge'

### ISSUE THREAD

**Issue by pbr90x** [nzapponi/homebridge-simplisafe3#70]
I just updated my simplisafe3 plugin today, and there may have been a bug introduced that breaks the ability to use a non-default homebridge home directory specified w/ the -U command-line option. I had updated my Node.js install just a few days ago, so this change was recent. It looks like the plugin is no longer respecting the directory passed w/ -U when starting up.

I have had Homebridge running on Raspbian Buster as a systemd service with no problems. I use `/var/lib/homebridge` as the homebridge user directory, with this being passed to homebridge when systemd launches the service using the -U command-line option. This comes from the `$HOMEBRIDGE_OPTS` environmental variable that is sourced from `/etc/default/homebridge` and referenced in `/lib/systemd/system/homebridge.service` (`ExecStart=/usr/bin/homebridge $HOMEBRIDGE_OPTS`). Just standard systemd stuff that has been working smoothly for me since I first set this up months ago.

As soon as I updated to the latest simplisafe3 plugin release using npm the service started failing to launch, with a failed `mkdir '/home/homebridge/.homebridge'` command seemingly the problem. Stack trace below:

```
Feb 01 12:22:41 raspberrypi homebridge[3193]: [2/1/2020, 12:22:41] Error: ENOENT: no such file or directory, mkdir '/home/homebridge/.homebridge'
Feb 01 12:22:41 raspberrypi homebridge[3193]:     at Object.mkdirSync (fs.js:823:3)
Feb 01 12:22:41 raspberrypi homebridge[3193]:     at new SimpliSafe3 (/usr/lib/node_modules/homebridge-simplisafe3/simplisafe.js:178:19)
Feb 01 12:22:41 raspberrypi homebridge[3193]:     at new SS3Platform (/usr/lib/node_modules/homebridge-simplisafe3/index.js:65:23)
Feb 01 12:22:41 raspberrypi homebridge[3193]:     at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:337:32)
Feb 01 12:22:41 raspberrypi homebridge[3193]:     at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
Feb 01 12:22:41 raspberrypi homebridge[3193]:     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
Feb 01 12:22:41 raspberrypi homebridge[3193]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Feb 01 12:22:41 raspberrypi homebridge[3193]:     at Module._compile (internal/modules/cjs/loader.js:955:30)
Feb 01 12:22:41 raspberrypi homebridge[3193]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
Feb 01 12:22:41 raspberrypi homebridge[3193]:     at Module.load (internal/modules/cjs/loader.js:811:32)
Feb 01 12:22:41 raspberrypi homebridge[3193]: [2/1/2020, 12:22:41] Got SIGTERM, shutting down Homebridge...
```

There seems to be a new file being created under `.homebridge`, with a mkdir call that isn't respecting the value passed through -U at the command-line:

```
pi@raspberrypi:/home $ ls -al /var/lib/homebridge/.homebridge/
total 12
drwxr-xr-x 2 homebridge homebridge 4096 Feb  1 12:23 .
drwxr-xr-x 5 homebridge homebridge 4096 Feb  1 12:23 ..
-rw-r--r-- 1 homebridge homebridge   22 Feb  1 12:23 .simplisafe3.conf

pi@raspberrypi:/home $ cat /var/lib/homebridge/.homebridge/.simplisafe3.conf
{"ssId":"REDACTED"}
```

I did a bunch of troubleshooting with no luck. Finally I decided to just symlink /home/homebridge to /var/lib/homebridge and now the service starts again.

**Comment by nzapponi** [comment]
Please confirm if it's not been fixed by v1.4.4!
