### ISSUE TITLE
Camera's not going away

### ISSUE THREAD

**Issue by afalahi** [nzapponi/homebridge-simplisafe3#77]
I've recently returned the SS3 cameras to SimpliSafe. From a "decoupling" perspective, this is what I did:

1. I removed each camera physically from my house

1. I removed all cameras from my SS via the App

1. Restarted HB

the restart didn't help, so I did the following:

- Switched persistAccessories to false, didn't help

- Deleted the Accessory and Persist folder in HB, rebooted, didn't help

- Unselected the Camera checkbox (checked the config file as well) in the plugin, but didn't help

- Removed HB (lost all my automations :(  ), added it back, also didn't help.

At this point, I'm lost and not sure what else could be caching the camera's even after I removed HB and added it back, I could reset/change the username and pairing pin, but I'd rather know for sure that this will fix it. Did anyone run into this?

**Comment by nzapponi** [comment]
Hi @afalahi , sorry you went through all of that...
Have you tried to go into the Home app, tap on Edit, tap on the camera and choose "Remove camera from Home"?

**Comment by afalahi** [comment]
lmao brooooooooooooo I feel so dumb now, I didn't realize I could do that thought all HB accessories are controlled via the bridge. They're gone now, I cannot believe I did all these steps without checking lol. Thanks for the help!

**Comment by nzapponi** [comment]
No worries! Lol!!
In general you're right, all accessories should be managed via the bridge.

However, due to limitations in Homebridge, cameras are outside of that and appear as standalone accessories, meaning that you can add and remove them independently of your Homebridge bridge!

Glad it helped!
