### ISSUE TITLE
Excluding Sensors

### ISSUE THREAD

**Issue by jparchem** [nzapponi/homebridge-simplisafe3#78]
Hello

I'm experiencing exactly the same issue as [#54 Repeated No Response](https://github.com/nzapponi/homebridge-simplisafe3/issues/54)

I haven't run into this issue on any non-simplisafe device.  They all update properly.

I'd actually just like to have the ability to arm/disarm without exposing the sensors to HomeKit.  Is there a way to do that?

**Comment by nikonratm** [comment]
@jparchem it would be pretty straightforward to implement a toggle like you described but there is a high chance you would still have “No Response” issues even without the sensors enabled.

In my experience these issues are often related to networking and / or a homebridge setup itself. In other words probably are not just this plugin.

Here’s a somewhat detailed write-up that might help: https://reddit.com/r/homebridge/comments/f1gmjq/things_i_did_that_eventually_worked_to_make_my/

**Comment by jparchem** [comment]
Thanks for the help and a great plug-in.  I ended up totally rebuilding my Rasp Pi Homebridge and the issue seems to be resolved.  Probably something out-of-date.
