### ISSUE TITLE
Feature Request: Exclude sensor by ID

### ISSUE THREAD

**Issue by muzzymate** [nzapponi/homebridge-simplisafe3#79]
Any thoughts on adding a feature to exclude a particular sensor? If implemented, I would imagine a new array in the config.json configuration that identifies the sensor by serial number. The plugin would then not surface that particular sensor to Homekit if it matches the serial number in the array. 

"exclude":  [ "00123456", "00123457" ],

My particular use case: I have an August Gen 2 door llock that includes a door sense sensor. The August is exposed through the Smartthings homebridge plugin, since it's the non-Homekit native version. I also have a door sensor to trigger an alarm to the Simplisafe system, if armed. As a result, I have two "front door sensors". The August door sensor triggers immediately and more consistently because of the features supported in that plugin and it's push integration.

Not the end of the world to have two front door sensors, but just keeps things tidier. Thanks!

**Comment by nikonratm** [comment]
Seems like an extremely specific use case IMHO. You can just remove one of the sensors from your favorites / put it in another room in HomeKit, no?

**Comment by muzzymate** [comment]
Yes, I go back and forth between having a junk room or simply living with the two sensors. I'll close out this request if other use cases aren't apparent.
