### ISSUE TITLE
Homebridge Crash

### ISSUE THREAD

**Issue by JoshuaHolme** [nzapponi/homebridge-simplisafe3#80]
This is the only plugin I have installed in home bridge, and it periodically crashes, leaving this error in the console 
<img width="689" alt="Screen Shot 2020-02-15 at 11 21 12 AM" src="https://user-images.githubusercontent.com/25995502/74591368-6f33eb00-4fe5-11ea-9862-ca446a10f1fe.png">

**Comment by nikonratm** [comment]
@JoshuaHolme this is the same issue as #64 , if you wouldn't mind closing this one and I will reply there.
