### ISSUE TITLE
Cameras not working after update

### ISSUE THREAD

**Issue by britishxninja** [nzapponi/homebridge-simplisafe3#82]
I just updated to the latest version after falling several iterations behind. Now, suddenly my camera won’t stream, and I’m receiving this error 
```
TypeError: Cannot read property 'getCharacteristic' of undefined
    at SS3SimpliCam.setAccessory (/usr/local/lib/node_modules/homebridge-simplisafe3/accessories/simplicam.js:64:76)
    at /usr/local/lib/node_modules/homebridge-simplisafe3/index.js:128:18
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
 ```

**Comment by nikonratm** [comment]
Depending on which version you were on there were major changes to the camera setup and they now need to be added separately so you may need to re-add them. To solve the error please clear cachedAccessories and persist folder (note this will remove your accessories)

https://github.com/nzapponi/homebridge-simplisafe3/issues/71

**Comment by britishxninja** [comment]
Oh thanks! That fixed it!
