### ISSUE TITLE
Camera stream not working on HOOBS.

### ISSUE THREAD

**Issue by calebcaudill** [nzapponi/homebridge-simplisafe3#89]
[Homebridge] [4/6/2020, 7:24:53 PM] [Home Alarm] Start streaming video from Doorbell
[Homebridge] [4/6/2020, 7:24:53 PM] [Home Alarm] ffmpeg version N-96428-ga8ceb2a72f Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (Raspbian 8.3.0-6+rpi1)
  configuration: --arch=armel --target-os=linux --enable-omx-rpi --enable-nonfree --enable-gpl --enable-libfdk-aac --enable-mmal --enable-libx264 --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-demuxer=rtsp
[Homebridge] [4/6/2020, 7:24:53 PM] [Home Alarm]   libavutil      56. 38.100 / 56. 38.100
  libavcodec     58. 66.100 / 58. 66.100
  libavformat    58. 35.103 / 58. 35.103
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 71.100 /  7. 71.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
[Homebridge] [4/6/2020, 7:24:54 PM] [Home Alarm] https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.
https://52.87.36.43/v1/c4ed1f828c4814d10f9c2473e00b36ef/flv?x=1280: Protocol not found
Did you mean file:https://52.87.36.43/v1/c4ed1f828c4814d10f9c2473e00b36ef/flv?x=1280?
[Homebridge] [4/6/2020, 7:24:54 PM] [Home Alarm] Error: FFmpeg exited with code 1
[Homebridge] [4/6/2020, 7:25:20 PM] [Home Alarm] Handling snapshot for Doorbell at 480x270
[Homebridge] [4/6/2020, 7:25:20 PM] [Home Alarm] Handling snapshot for Upstairs at 480x270
[Homebridge] [4/6/2020, 7:25:20 PM] [Home Alarm] /usr/local/bin/ffmpeg-re,-headers,Authorization: Bearer y10iF8OU3JMR40ps3q1i/auYi3cIXa4HT3Hd0THJ4SI=,-i,https://52.87.36.43/v1/c4ed1f828c4814d10f9c2473e00b36ef/flv?x=480,-t,1,-s,480x270,-f,image2,-vframes,1,-
[Homebridge] [4/6/2020, 7:25:20 PM] [Home Alarm] Close Doorbell stream with image of length: 0
[Homebridge] [4/6/2020, 7:25:20 PM] [Home Alarm] /usr/local/bin/ffmpeg-re,-headers,Authorization: Bearer y10iF8OU3JMR40ps3q1i/auYi3cIXa4HT3Hd0THJ4SI=,-i,https://52.87.36.43/v1/8591ad234de0a302fcbacd03700c05e1/flv?x=480,-t,1,-s,480x270,-f,image2,-vframes,1,-
[Homebridge] [4/6/2020, 7:25:20 PM] [Home Alarm] Close Upstairs stream with image of length: 0
[Homebridge] [4/6/2020, 7:25:42 PM] [Home Alarm] Handling snapshot for Doorbell at 480x270
[Homebridge] [4/6/2020, 7:25:42 PM] [Home Alarm] /usr/local/bin/ffmpeg-re,-headers,Authorization: Bearer y10iF8OU3JMR40ps3q1i/auYi3cIXa4HT3Hd0THJ4SI=,-i,https://52.87.36.43/v1/c4ed1f828c4814d10f9c2473e00b36ef/flv?x=480,-t,1,-s,480x270,-f,image2,-vframes,1,-
[Homebridge] [4/6/2020, 7:25:42 PM] [Home Alarm] Close Doorbell stream with image of length: 0

**Comment by nikonratm** [comment]
Duplicate for https://github.com/nzapponi/homebridge-simplisafe3/issues/72

**Comment by calebcaudill** [comment]
Issue resolved. Per HOOBS developer instructions, running this fixed it:

`wget -q -O - http://bit.ly/get-ffmpeg | sudo bash -`
