### ISSUE TITLE
Enhancement: Support Homebridge v1.0.0 Features

### ISSUE THREAD

**Issue by nikonratm** [nzapponi/homebridge-simplisafe3#96]
https://github.com/homebridge/homebridge/releases/tag/1.0.0
Of interest:
- Bridged cameras are now supported, have to figure out what to do with existing setups.
- ~~DynamicPlatformPlugin!~~ EDIT: this is not a new implementation no changes needed
- CameraController API
- More?

Worried this is gonna be a bit painful...

**Comment by nzapponi** [comment]
Yeah it will be painful. Let me look into Homebridge v1.0.0 and let's see what major things we need to edit.
I'm excited about bridged cameras though!

**Comment by nzapponi** [comment]
I don't know if you remember, but in the past I had initially implemented bridged cameras, unaware that Homebridge still didn't support them. The main issue was around snapshots and rich camera notifications.

I can revive that code if you want to, or you can make the changes (I see you're already working on it!). Up to you!

**Comment by nzapponi** [comment]
By the way, as far as I can tell, our plugin is already using dynamic platforms, right?

**Comment by nikonratm** [comment]
Yea I started a branch in my fork (since I dont have access to this one) where I got the bridge stuff working, my biggest question is how its going to play with existing setups, I've asked around about that. And yes I guess I misread the dynamic platform as something new so seems like we get new benefits without much work there.

FWIW, plugin seems to work (I think?) with v1.0.0 out-of-the box so thats great!

**Comment by nikonratm** [comment]
Oh wait, I lied, I think t[he changes to `identify`](https://github.com/nikonratm/homebridge-simplisafe3/commit/8eee6edb5430f099df2e9d20ff6d1b47dca8e9b2) are needed for compatibility.

**Comment by nzapponi** [comment]
Ok, no worries, how about you work on bridged cameras support and breaking changes, and I'll set up some GitHub Actions to automate publishing to npm so I can then give you write access to this repo? I've been hesitant mostly around the process of publishing to npm. We could even set up a team, now that they're free!

**Comment by nikonratm** [comment]
Totally down for that! If I can work in the real repo I will always work in branches and wont mess with master =)

**Comment by nikonratm** [comment]
So in my testing it seems like the transition wont be that "graceful" for cameras. Basically, when we convert them to bridged the existing cameras will become giant "Not Responding" tiles in the Home.app but new ones will automatically be added. Obviously we can update documentation etc. and hopefully it will be kinda obvious to people they'll need to delete the old ones. That also means people will lose their automations too which is sorta annoying. But I dont really see any way around this, do you? The old cameras aren't even cached because that was broken before so its not like we could 'detect' them or anything...

I figured out the `identify` thing, seems to come from https://github.com/homebridge/homebridge/blob/34f18ff30434d58e58b9d11248210ba0937014b4/src/server.ts#L433 (function is called with just an empty callback not `paired`). I cant tell if thats a bug or not but anyway, fixed.

Maybe not so bad?!

**Comment by nikonratm** [comment]
Btw, because of these the new version will also be backwards-incompatible with homebridge. I guess the options would be to build in legacy support though seems unnecessary or we release one last version that requires Homebridge < 1.0.0 and then release a new version that requires >= 1.0.0, yea?

**Comment by nikonratm** [comment]
I started a [second branch](https://github.com/nikonratm/homebridge-simplisafe3/tree/hap-cameracontrollerapi) for the CameraController API because thats a big change (but its sorta working actually!) but the [homebridge-v1.0](https://github.com/nikonratm/homebridge-simplisafe3/tree/homebridge-v1.0) branch seems to pretty much be compatible with v1.0.0 and includes bridged cameras and some other tweaks

**Comment by nzapponi** [comment]
Great stuff, thanks! I'm not sure if there's a way to specify in the package that the next version should only be downloaded if homebridge >= 1.0, otherwise download the old one.. I can look into it.

This week I'm too busy to test this out, but if you could keep iterating on it, we can then test and release sometime next week?

**Comment by nzapponi** [comment]
@nikonratm you now have push access to master. I still recommend going through pull requests as there's a CI action which checks for linting etc on pull requests.

When you're ready to publish on npm, follow this process:
- Update the changelog
- Run `npm version v1.x.x` in your repo, then open the pull request and merge into master
- Finally, in GitHub, click on the Releases tab inside Code, click on Draft a new release, pick the correct version you created and choose **Publish Release**. That will publish to npm!

Let me know if you run into any issues and thanks for all the work!

**Comment by nikonratm** [comment]
Can you specify it with the [`engines` config](https://docs.npmjs.com/files/package.json#engines ) in package.json or nah?

Yea Im not in a particular rush to release this, v1.0 stuff is always buggy anyway.

Thanks for write access! I guess I'll push those two branches over here 👍🏼

**Comment by nzapponi** [comment]
Yes, engines should be the right way to go about it, but if someone is on Homebridge 0.x, would it still download the older version or would it just error out saying it's not compatible?

No big deal, we can always specify in the readme anyway.
I'll test things out over the coming weeks and we'll decide when to release!

**Comment by nikonratm** [comment]
I think they changed it in 1.0.1 so that it just logs a warning ( https://github.com/homebridge/homebridge/pull/2522 ) but that might change soon too. Sounds good, no rush!

**Comment by nikonratm** [comment]
Ok I think the camera stuff is working so I merged it back into the [homebridge-v1.0 branch](https://github.com/nzapponi/homebridge-simplisafe3/tree/homebridge-v1.0). I updated readme with some info on upgrading cameras as well. 

I figure this is worthy of a minor version bump to 1.5.0 especially since its basically breaking changes. 

I will keep testing to see if any issues crop up and until we're ready to release.

**Comment by nikonratm** [comment]
Hey this seems pretty good in my testing so far so I submitted the PR. Obviously the part I'd most want to test is the "onboarding" process which is a little cumbersome to test but seemed to work OK (and I updated readme etc. accordingly). 

No rush!
